### PR TITLE
Update nu.txt

### PR DESCRIPTION
**Pull request by boltsandbombers**
Chimecho: removed
Aurorus: removed dual dance set and removed thunderbolt from specs in exchange for Psychic
Mawile: Jolly -> Adamant and added defensive set
Snasel: Ice Punch -> Icicle Crash
Magmortar: removed choice and expert belt (plays almost exactly the same as life orb) sets and added assault vest set
Electivire: Cross Chop -> Earthquake
Exeggutor: Fixed ev spread on lumrest, too much creep and removed sub leech seed set
Garbodor: added offensive set and changed Toxic -> Toxic Spikes on defensive set
Gurdurr: fixed moveset for second set (it didnt have knock off and ice punch is bad) as well as updating the ev spreads to a much more efficient one
Kabutops: removed weakness policy set
Kangaskhan: Drain punch -> Earthquake on silk scarf set
Lilligant: removed lum berry lilligant set because the item itself isnt very good on lilligant and the set doesn't play differently from life orb
Primeape: removed choice scarf because its awful
Regirock: condensed both sets into one and c/ped the one from the dex because the moveset and evs are better
Rhydon: Roar -> Megahorn on tank set
Weezing: removed specs set (joke set)
Zangoose: removed the second set because protect is really bad
Quagsire: added curse set
Claydol: swapped defensive set for offensive
Audino: added offensive Calm Mind Mega Audino
Cacturne: added mixed set and fixed SD set by changing jolly to adamant and focus sash to life orb
Cryogonal: updated defensive set's ev spread (used to have enough speed for adamant gatr)
Golurk: updated sets based on new analysis [specific changes: max spe on choice band, max spe on stealth rock, added rock polish set]
Carbink: added Trick Room set, removed sunny day set
Swellow: Protect -> Quick Attack on Guts set
Sawk: Changed the Choice Band set to Sturdy with the dex's moveset and swapped Poison Jab for Earthquake on Scarf set
Cradily: removed the set without stealth rock
Xatu: removed the two sets (no speed and spdef are both bad as well as life orb) and put in the standard-ish sets from the analysis
Articuno: Substitute -> HP Fire on Life Orb set
Bearctic: removed
Armaldo: removed
Miltank: removed life orb set
Liepard: removed weather setting sets
Klinkalng: removed lum berry set
Mantine: removed rest talk set and the fully specially defensive spread, added defensive set from the dex
Mesprit: added physical choice scarf set, fixed special scarf set as it didn't have healing wish and HP fire isn't good on scarf
Mismagius: swapped destiny bond for nasty plot on the life orb set, as the two current offensive sets were nearly identical and neither had nasty plot in the first place. Fixed EV spread on stallbreaker set because base 100 Pokemon are scarce, dropped Speed to be ahead of base 95s.
Rotom: swapped sub split set for the wisp + Hex set
Pyroar: removed choice scarf set
Kabutops: Knock Off -> Waterfall on spin 3 attacks set
Uxie: removed weather setting sets and updated sets to current metagame (max speed on dual screens, 56 spe on pivot set, and cm 3 attacks over sub cm)
Pawniard: removed life orb set
 
Below are Pokemon that I added new entries for as they were not in the file despite being good Pokemon in NU
 
Scyther: Added SD and CB sets
Torterra: Added CB, Rock Polish, and tank sets
Haunter: Added LO and Scarf sets
Prinplup: added standard set
Tangela: added offensive and defensive sets
Pelipper: added defensive set
Piloswine: added tank set
Poliwrath: added life orb and rest talk sets

### CODE REVIEW

**Comment by TheImmortal** [comment]
Move slashes are a thing now fyi.

**Comment by boltsandbombers** [comment]
Oh, thats really helpful. So like if Megahorn was slashed with Roar on Rhydon you'd have a 50/50 chance of getting each one?
I can re-do some of the changes if need be now that I know that.

**Comment by TheImmortal** [comment]
Yes. But don't repeat moves in the same set.

**Comment by WreckDra** [comment]
Your build failed because you have Audino's Mega Stone spelled as "Audinoite" instead of "Audinite" which is the correct spelling. 

I am also going to echo what @Slayer95 said to me with my updates in that any hazard control moves (Stealth Rock / Spikes / Toxic Spikes / Sticky Web / Defog / Rapid Spin) cannot be slashed with due to a feature in the team generator that this would confuse. I was told to create separate sets for Pokemon with hazard control slashes and I infer that this is also the case here.

**Comment by boltsandbombers** [comment]
Alright, thanks for the catch. Fixed all the slashing and spelling errors and and tweaked a few sets. According to the Travis CI build thing above this should be good to go.

**Pull request merged**
